  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module stars::stars_deploy_hook {

  use stars::stars_schema::Schema;

  public(package) fun run(_schema: &mut Schema, _ctx: &mut TxContext) {}
}
